Document: wago-popup-dict
Title: Debian wago-popup-dict Manual
Author: <insert document author here>
Abstract: This manual describes what wago-popup-dict is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/wago-popup-dict/wago-popup-dict.sgml.gz

Format: postscript
Files: /usr/share/doc/wago-popup-dict/wago-popup-dict.ps.gz

Format: text
Files: /usr/share/doc/wago-popup-dict/wago-popup-dict.text.gz

Format: HTML
Index: /usr/share/doc/wago-popup-dict/html/index.html
Files: /usr/share/doc/wago-popup-dict/html/*.html
