
public class Wordstem {

        public static string find_stem_form(string japanese_word) {
                for(int i=0; i<entry_count; i++) {
                        if(japanese_word.length > stem_transformation[i*3].length) {
                                string tmp = japanese_word.substring(japanese_word.length-stem_transformation[i*3].length);
                                if(tmp == stem_transformation[i*3]) {
                                        tmp = japanese_word.substring(0, tmp.length);
                                        tmp = tmp.concat(stem_transformation[i*3+1]);
                                        return tmp;
                                }
                        }
                }
                return "";
        }
        
        //not needed ATM TODO: translate to english look into il8n
        const string wordtype_german[] =
        {
        "förmlich verneinte Vergangenheit",
        "förmlich verneint",
        "förmlich intentional",
        "-chau",
        "-sugiru",
        "-nasai",
        "förmlich Vergangenheit",
        "-tara",
        "-tari",
        "kausal",
        "potential oder passive",
        "-sou",
        "-tai",
        "förmlich",
        "Vergangenheit",
        "negativ",
        "passiv",
        "-ba",
        "intentional",
        "potential",
        "passiv oder kausal",
        "-te",
        "-zu",
        "Imperativ",
        "masu Stamm",
        "adv",
        "nomen",
        "Imperativ verneint",
        "potential oder passive Vergangenheit"
        };


        private const int entry_count = 308;
        
        const string stem_transformation[] =
        {
        "くありませんでした","い",(string) 0,
        "いませんでした","う",(string)0,
        "きませんでした","く",(string)0,
        "きませんでした","くる",(string)0,
        "ぎませんでした","ぐ",(string)0,
        "しませんでした","す",(string)0,
        "しませんでした","する",(string)0,
        "ちませんでした","つ",(string) 0,
        "にませんでした","ぬ",(string) 0,
        "びませんでした","ぶ",(string) 0,
        "みませんでした","む",(string) 0,
        "りませんでした","る",(string) 0,
        "くありません","い",(string) 1,
        "ませんでした","る",(string) 0,
        "いましょう","う",(string) 2,
        "きましょう","く",(string) 2,
        "きましょう","くる",(string) 2,
        "ぎましょう","ぐ",(string) 2,
        "しましょう","す",(string) 2,
        "しましょう","する",(string) 2,
        "ちましょう","つ",(string) 2,
        "にましょう","ぬ",(string) 2,
        "びましょう","ぶ",(string) 2,
        "みましょう","む",(string) 2,
        "りましょう","る",(string) 2,
        "いじゃう","ぐ",(string) 3,
        "いすぎる","う",(string) 4,
        "いちゃう","く",(string) 3,
        "いなさい","う",(string) 5,
        "いました","う",(string) 6,
        "いません","う",(string) 1,
        "かったら","い",(string) 7,
        "かったり","い",(string) 8,
        "きすぎる","く",(string) 4,
        "きすぎる","くる",(string) 4,
        "ぎすぎる","ぐ",(string) 4,
        "きちゃう","くる",(string) 3,
        "きなさい","く",(string) 5,
        "きなさい","くる",(string) 5,
        "ぎなさい","ぐ",(string) 5,
        "きました","く",(string) 6,
        "きました","くる",(string) 6,
        "ぎました","ぐ",(string) 6,
        "きません","く",(string) 1,
        "きません","くる",(string) 1,
        "ぎません","ぐ",(string) 1,
        "こさせる","くる",(string) 9,
        "こられる","くる",(string) 10,
        "しすぎる","す",(string) 4,
        "しすぎる","する",(string) 4,
        "しちゃう","す",(string) 3,
        "しちゃう","する",(string) 3,
        "しなさい","す",(string) 5,
        "しなさい","する",(string) 5,
        "しました","す",(string) 6,
        "しました","する",(string) 6,
        "しません","す",(string) 1,
        "しません","する",(string) 1,
        "ちすぎる","つ",(string) 4,
        "ちなさい","つ",(string) 5,
        "ちました","つ",(string) 6,
        "ちません","つ",(string) 1,
        "っちゃう","う",(string) 3,
        "っちゃう","く",(string) 3,
        "っちゃう","つ",(string) 3,
        "っちゃう","る",(string) 3,
        "にすぎる","ぬ",(string) 4,
        "になさい","ぬ",(string) 5,
        "にました","ぬ",(string) 6,
        "にません","ぬ",(string) 1,
        "びすぎる","ぶ",(string) 4,
        "びなさい","ぶ",(string) 5,
        "びました","ぶ",(string) 6,
        "びません","ぶ",(string) 1,
        "ましょう","る",(string) 2,
        "みすぎる","む",(string) 4,
        "みなさい","む",(string) 5,
        "みました","む",(string) 6,
        "みません","む",(string) 1,
        "りすぎる","る",(string) 4,
        "りなさい","る",(string) 5,
        "りました","る",(string) 6,
        "りません","る",(string) 1,
        "んじゃう","ぬ",(string) 3,
        "んじゃう","ぶ",(string) 3,
        "んじゃう","む",(string) 3,
        "いそう","う",(string) 11,
        "いたい","う",(string) 12,
        "いたら","く",(string) 7,
        "いだら","ぐ",(string) 7,
        "いたり","く",(string) 8,
        "いだり","ぐ",(string) 8,
        "います","う",(string) 13,
        "かせる","く",(string) 9,
        "がせる","ぐ",(string) 9,
        "かった","い",(string) 14,
        "かない","く",(string) 15,
        "がない","ぐ",(string) 15,
        "かれる","く",(string) 16,
        "がれる","ぐ",(string) 16,
        "きそう","く",(string) 11,
        "きそう","くる",(string) 11,
        "ぎそう","ぐ",(string) 11,
        "きたい","く",(string) 12,
        "きたい","くる",(string) 12,
        "ぎたい","ぐ",(string) 12,
        "きたら","くる",(string) 7,
        "きたり","くる",(string) 8,
        "きます","く",(string) 13,
        "きます","くる",(string) 13,
        "ぎます","ぐ",(string) 13,
        "くない","い",(string) 15,
        "ければ","い",(string) 17,
        "こない","くる",(string) 15,
        "こよう","くる",(string) 18,
        "これる","くる",(string) 19,
        "させる","する",(string) 9,
        "させる","る",(string) 9,
        "さない","す",(string) 15,
        "される","す",(string) 20,
        "される","する",(string) 16,
        "しそう","す",(string) 11,
        "しそう","する",(string) 11,
        "したい","す",(string) 12,
        "したい","する",(string) 12,
        "したら","す",(string) 7,
        "したら","する",(string) 7,
        "したり","す",(string) 8,
        "したり","する",(string) 8,
        "しない","する",(string) 15,
        "します","す",(string) 13,
        "します","する",(string) 13,
        "しよう","する",(string) 18,
        "すぎる","い",(string) 4,
        "すぎる","る",(string) 4,
        "たせる","つ",(string) 9,
        "たない","つ",(string) 15,
        "たれる","つ",(string) 16,
        "ちそう","つ",(string) 11,
        "ちたい","つ",(string) 12,
        "ちます","つ",(string) 13,
        "ちゃう","る",(string) 3,
        "ったら","う",(string) 7,
        "ったら","つ",(string) 7,
        "ったら","る",(string) 7,
        "ったり","う",(string) 8,
        "ったり","つ",(string) 8,
        "ったり","る",(string) 8,
        "なさい","る",(string) 5,
        "なせる","ぬ",(string) 9,
        "なない","ぬ",(string) 15,
        "なれる","ぬ",(string) 16,
        "にそう","ぬ",(string) 11,
        "にたい","ぬ",(string) 12,
        "にます","ぬ",(string) 13,
        "ばせる","ぶ",(string) 9,
        "ばない","ぶ",(string) 15,
        "ばれる","ぶ",(string) 16,
        "びそう","ぶ",(string) 11,
        "びたい","ぶ",(string) 12,
        "びます","ぶ",(string) 13,
        "ました","る",(string) 6,
        "ませる","む",(string) 9,
        "ません","る",(string) 1,
        "まない","む",(string) 15,
        "まれる","む",(string) 16,
        "みそう","む",(string) 11,
        "みたい","む",(string) 12,
        "みます","む",(string) 13,
        "らせる","る",(string) 9,
        "らない","る",(string) 15,
        "られる","る",(string) 10,
        "られた","る",(string) 28,
        "りそう","る",(string) 11,
        "りたい","る",(string) 12,
        "ります","る",(string) 13,
        "わせる","う",(string)9,
        "わない","う",(string) 15,
        "われる","う",(string) 16,
        "んだら","ぬ",(string) 7,
        "んだら","ぶ",(string) 7,
        "んだら","む",(string) 7,
        "んだり","ぬ",(string) 8,
        "んだり","ぶ",(string) 8,
        "んだり","む",(string) 8,
        "いた","く",(string) 14,
        "いだ","ぐ",(string) 14,
        "いて","く",(string) 21,
        "いで","ぐ",(string) 21,
        "えば","う",(string) 17,
        "える","う",(string) 19,
        "おう","う",(string) 18,
        "かず","く",(string) 22,
        "がず","ぐ",(string) 22,
        "きた","くる",(string) 14,
        "きて","くる",(string) 21,
        "くて","い",(string) 21,
        "けば","く",(string) 17,
        "げば","ぐ",(string) 17,
        "ける","く",(string) 19,
        "げる","ぐ",(string) 19,
        "こい","くる",(string) 23,
        "こう","く",(string) 18,
        "ごう","ぐ",(string) 18,
        "こず","くる",(string) 22,
        "さず","す",(string) 22,
        "した","す",(string) 14,
        "した","する",(string) 14,
        "して","す",(string) 21,
        "して","する",(string) 21,
        "しろ","する",(string) 23,
        "せず","する",(string) 22,
        "せば","す",(string) 17,
        "せよ","する",(string) 23,
        "せる","す",(string) 19,
        "そう","い",(string) 11,
        "そう","す",(string) 18,
        "そう","る",(string) 11,
        "たい","る",(string) 12,
        "たず","つ",(string) 22,
        "たら","る",(string) 7,
        "たり","る",(string) 8,
        "った","う",(string) 14,
        "った","く",(string) 14,
        "った","つ",(string) 14,
        "った","る",(string) 14,
        "って","う",(string) 21,
        "って","く",(string) 21,
        "って","つ",(string) 21,
        "って","る",(string) 21,
        "てば","つ",(string) 17,
        "てる","つ",(string) 19,
        "とう","つ",(string) 18,
        "ない","る",(string) 15,
        "なず","ぬ",(string) 22,
        "ねば","ぬ",(string) 17,
        "ねる","ぬ",(string) 19,
        "のう","ぬ",(string) 18,
        "ばず","ぶ",(string) 22,
        "べば","ぶ",(string) 17,
        "べる","ぶ",(string) 19,
        "ぼう","ぶ",(string) 18,
        "ます","る",(string) 13,
        "まず","む",(string) 22,
        "めば","む",(string) 17,
        "める","む",(string) 19,
        "もう","む",(string) 18,
        "よう","る",(string) 18,
        "らず","る",(string) 22,
        "れば","る",(string) 17,
        "れる","る",(string) 19,
        "ろう","る",(string) 18,
        "わず","う",(string) 22,
        "んだ","ぬ",(string) 14,
        "んだ","ぶ",(string) 14,
        "んだ","む",(string) 14,
        "んで","ぬ",(string) 21,
        "んで","ぶ",(string) 21,
        "んで","む",(string) 21,
        "い","いる",(string) 24,
        "い","う",(string) 24,
        "い","る",(string) 23,
        "え","う",(string) 23,
        "え","える",(string) 24,
        "き","きる",(string) 24,
        "き","く",(string) 24,
        "ぎ","ぎる",(string) 24,
        "ぎ","ぐ",(string) 24,
        "く","い",(string) 25,
        "け","く",(string) 23,
        "け","ける",(string) 24,
        "げ","ぐ",(string) 23,
        "げ","げる",(string) 24,
        "さ","い",(string) 26,
        "し","す",(string) 24,
        "じ","じる",(string) 24,
        "ず","る",(string) 22,
        "せ","す",(string) 23,
        "せ","せる",(string) 24,
        "ぜ","ぜる",(string) 24,
        "た","る",(string) 14,
        "ち","ちる",(string) 24,
        "ち","つ",(string) 24,
        "て","つ",(string) 23,
        "て","てる",(string) 24,
        "て","る",(string) 21,
        "で","でる",(string) 24,
        "な","",(string) 27,
        "に","にる",(string) 24,
        "に","ぬ",(string) 24,
        "ね","ぬ",(string) 23,
        "ね","ねる",(string) 24,
        "ひ","ひる",(string) 24,
        "び","びる",(string) 24,
        "び","ぶ",(string) 24,
        "へ","へる",(string) 24,
        "べ","ぶ",(string) 23,
        "べ","べる",(string) 24,
        "み","みる",(string) 24,
        "み","む",(string) 24,
        "め","む",(string) 23,
        "め","める",(string) 24,
        "よ","る",(string) 23,
        "り","りる",(string) 24,
        "り","る",(string) 24,
        "れ","る",(string) 23,
        "れ","れる",(string) 24,
        "ろ","る",(string)23
        };

}
